### ISSUE TITLE
Can't see "last survey day" when zoomed in on hiking map.

### ISSUE THREAD

**Issue by hgcvm** [vmarc/knooppuntnet#121]
When zoomed in at the route planner for hiking, the map "hangs" when trying to select "Date last survey" radio button. I can't see the nodes and links anymore and also cannot move the map. 

This problem does not happen on the map for cycling. 

I tried it both with Firefox and Chromium on the same computer. 

Let me know if I need to provide additional information.

**Comment by hgcvm** [comment]
When going to the "analyzer" section of the website, I see "Sorry, cannot connect to server at this moment, please try again later. (502 - Bad Gateway)". Perhaps that's related to eachother. Might be a temporary problem.

**Comment by hgcvm** [comment]
Issue is gone. Might have been a temporary error.

**Comment by vmarc** [comment]
@hgcvm thanks for reporting this problem

What you observed is correct: the server application was down for about 3 hours on Sunday (OutOfMemoryError). The "Date last survey" function needs information from the server and as such could not work properly during that time. However, the route planner should handle this situation more gracefully.  The planner should not hang but report server unavailability instead.

By the way: experimental.knooppuntnet.nl/be were still functional.

Following stack trace was generated in the browser:

```
TypeError: this.mapService.surveyDateInfo() is null
  at surveyColor(webpack:/src/app/components/ol/style/survey-date-style.ts:17:36)
  at nodeColor(webpack:/src/app/components/ol/style/main-map-node-style.ts:102:36)
  at determineLargeNodeStyle(webpack:/src/app/components/ol/style/main-map-node-style.ts:57:24)
  at determineNodeMainStyle(webpack:/src/app/components/ol/style/main-map-node-style.ts:48:20)
  at nodeStyle(webpack:/src/app/components/ol/style/main-map-node-style.ts:29:24)
```
