### ISSUE TITLE
Knooppuntnet.be Uitvoer Link ongeldig

### ISSUE THREAD

**Issue by ina-vo** [vmarc/knooppuntnet#269]
Deze link komt van knooppuntnet.be en werd gekopieerd naar het klembord:

https://knooppuntnet.be/nl/map/hiking?plan=lrsyl6-49cwgb-49cwg4-49cwfq-hupkpb-lvmn1z-49cvvz-lvmmn6-lvmmgh-1cchpa3-26odhbe-ls6vbh-48fwv.2t-26odhbl-xpdr2o-48gdh.1-xpdr2i-16jquvq-lnauuz-e4yyes-e4yyde-e4yyd5-1u3s79p-e4yyb3-lnaveg-lxndsj-6echj6-lsesk8-49gfy6-o7xwz2-lrsyl6

PROBLEEM: **Deze link opent wel de website van knooppuntnet.be, maar de route wordt niet geladen.**
Getest met Opera op Android en Firefox en Chrome op Windows.
Andere routes hebben wel gewerkt.

Ik had het GPX bestand nodig en heb het via alternatieve weg overgebracht, dus geen hulp meer nodig.
Ik meld het probleem zodat het bekend gemaakt wordt.
Mvg

**Comment by vmarc** [comment]
@ina-vo dankjewel voor het melden van dit probleem, ik ga het verder onderzoeken

**Comment by vmarc** [comment]
Als ik de link lichtjes aanpas dan gaat het wel goed:

https://knooppuntnet.be/nl/map/hiking?plan=lrsyl6-49cwgb-49cwg4-49cwfq-hupkpb-lvmn1z-49cvvz-lvmmn6-lvmmgh-1cchpa3-26odhbe-ls6vbh-48fwv.2t-26odhbl-xpdr2o-xpdr2i-16jquvq-lnauuz-e4yyes-e4yyde-e4yyd5-1u3s79p-e4yyb3-lnaveg-lxndsj-6echj6-lsesk8-49gfy6-o7xwz2-lrsyl6&position=51.24899715,5.11400681,14

Het probleem zit ergens rond knooppunt 29, maar naar de juiste oorzaak moet ik nog verder zoeken.

![issue269](https://user-images.githubusercontent.com/6596480/192646550-250a82ec-bd04-4715-b2a5-e921995cf69f.png)

**Comment by vmarc** [comment]
Resultaat van verder onderzoek:

Het probleem doet zich voor wanneer bij het plannen van een wandeling, een selectie van een route tussen 2 knooppunten A en B direct gevolgd wordt de selectie van knooppunt B. 

Dat is mij gelukt door eerst een knooppunt voorbij de route selectie te kiezen, en daarna die selectie terug te slepen naar het eindpunt van geselecteerde route.  Bijvoorbeeld door volgende stappen te volgen:

1. klik op startpunt (in het voorbeeld knooppunt 34)

![stap1](https://user-images.githubusercontent.com/6596480/192847584-abc15cdb-83f9-4258-9a31-e67cfdfdb9af.png)

2. klik op route tussen 2 knooppunten (in het voorbeeld ergens tussen knooppunt 34 en 33 geklikt)

![stap2](https://user-images.githubusercontent.com/6596480/192847607-654fb845-ccbd-4456-99fc-052f76da99e9.png)

3. klik op knooppunt voorbij einde van in vorig punt aangeklikte route (in het voorbeeld knooppunt 32)

![stap3](https://user-images.githubusercontent.com/6596480/192847620-5f4681b7-a0f0-4d5d-af42-86ea4287d2c4.png)

4. klik op eindpunt (in het voorbeeld knooppunt 26)

![stap4](https://user-images.githubusercontent.com/6596480/192847626-2f897e14-081a-49cd-9082-587b58f6d4c6.png)

5. versleep de vlag van het knooppunt uit stap 3 naar einde van de route uit stap 2 (in het voorbeeld werd de vlag van 32 naar 33 verspleept)

![stap5](https://user-images.githubusercontent.com/6596480/192847642-19167d49-b2df-4bc2-b02c-1571f587d9eb.png)

6. klik "Uitvoer"

7. klik "Kopieer link naar klembord"

8. plak link in 2de browser tab adresbalk


In de browser console en netwerk log kun je nu zien dat knooppuntnet antwoord met http status code 500 (internal server error).

Op de server zelf komt er een foutmelding in de server log:
```
2022-09-28 00:24:29.836 INFO  http-nio-9005-exec-3 [] Api - Some(vmarc) plan(hiking: met3rw-26k05.2t-mep04w-13qxy6g) (11ms)
2022-09-28 00:24:29.840 ERROR http-nio-9005-exec-3 [] [dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.NoSuchElementException: last of empty list] with root cause
java.util.NoSuchElementException: last of empty list
at scala.collection.immutable.Nil$.last(List.scala:665) ~[scala-library-2.13.8.jar!/:?]
at scala.collection.immutable.Nil$.last(List.scala:661) ~[scala-library-2.13.8.jar!/:?]
at kpn.server.api.planner.leg.LegBuilderImpl.legEndsToPlanLegs(LegBuilderImpl.scala:88) ~[classes!/:4.0.7]
at kpn.server.api.planner.leg.LegBuilderImpl.plan(LegBuilderImpl.scala:46) ~[classes!/:4.0.7]
at kpn.server.api.planner.PlannerFacadeImpl.$anonfun$plan$1(PlannerFacadeImpl.scala:75) ~[classes!/:4.0.7]
at kpn.server.api.ApiImpl.execute(ApiImpl.scala:17) ~[classes!/:4.0.7]
at kpn.server.api.planner.PlannerFacadeImpl.plan(PlannerFacadeImpl.scala:74) ~[classes!/:4.0.7]
at kpn.server.api.planner.PlannerController.plan(PlannerController.scala:64) ~[classes!/:4.0.7]
```
