### ISSUE TITLE
Route map display problem

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#384]
When first zooming in to a route, and then zooming out at some point the map should change to show bitmap tiles instead of vector tiles.  The does not happen and instead vector tiles from higher zoom levels are used and the map becomes very slow (tries to show too many nodes/routes) util the browser crashes.

> ![image](https://github.com/vmarc/knooppuntnet/assets/6596480/f181f80b-4b95-456a-9e1f-77156de8f4a4)

> ![image](https://github.com/vmarc/knooppuntnet/assets/6596480/8f504087-88e3-47dc-8f5a-179260b26b73)

> ![image](https://github.com/vmarc/knooppuntnet/assets/6596480/0c028e97-dfd2-4679-a32c-16390ada0e05)

> ![image](https://github.com/vmarc/knooppuntnet/assets/6596480/57d368a0-7f97-4e8e-b70b-360e315ee296)

**Comment by vmarc** [comment]
In the logs, following errors can be found (unsure if any of these are related at all to this problem):

---

Error 1:

Stacktrace:

```
TypeError: Cannot read properties of undefined (reading 'includes')
  at forEach (./src/app/ol/services/openlayers-map-service.ts:157:36)
  at Array.forEach (<anonymous>)
  at OpenlayersMapService.updateLayerVisibility (./src/app/ol/services/openlayers-map-service.ts:147:20)
  at OpenlayersMapService.finalizeSetup (./src/app/ol/services/openlayers-map-service.ts:68:10)
  at RouteChangeMapService.init (./src/app/analysis/components/changes/route/route-change-map.service.ts:35:10)
...
(9 additional frame(s) were not displayed)
```
Code:

```
       const zoomInRange = zoom >= mapLayer.minZoom && zoom <= mapLayer.maxZoom;
        const visible =
          zoomInRange &&
          (mapLayerState.enabled || mapLayerState.layerName === mapLayer.name) &&
          mapLayerState.visible;
157>    if (visible && mapLayer.id.includes('vector') && mapLayer.layer.getVisible()) {
          mapLayer.layer.changed();
        }
        mapLayer.layer.setVisible(visible);
      }
    });

```

---

Error 2:

Stacktrace:

```
TypeError: Cannot read properties of undefined (reading 'clientX')
  at interaction_PinchZoom.PinchZoom.handleDragEvent (./node_modules/ol/interaction/PinchZoom.js:71:40)
  at Pointer.PointerInteraction.handleEvent (./node_modules/ol/interaction/Pointer.js:133:14)
  at ol_Map.Map.handleMapBrowserEvent (./node_modules/ol/Map.js:1153:34)
  at __WEBPACK_DEFAULT_EXPORT__.Target.dispatchEvent (./node_modules/ol/events/Target.js:114:11)
  at ol_MapBrowserEventHandler.MapBrowserEventHandler.handlePointerMove_ (./node_modules/ol/MapBrowserEventHandler.js:330:12)
...
(8 additional frame(s) were not displayed)
```
Code:

```
 handleDragEvent(mapBrowserEvent) {
    let scaleDelta = 1.0;
    const touch0 = this.targetPointers[0];
    const touch1 = this.targetPointers[1];
71> const dx = touch0.clientX - touch1.clientX;
    const dy = touch0.clientY - touch1.clientY;
    // distance between touches
    const distance = Math.sqrt(dx * dx + dy * dy);
```

---

Error 3:

Stacktrace:

```
TypeError: Cannot read properties of undefined (reading 'dispose')
  at OpenlayersMapService.destroy (./src/app/ol/services/openlayers-map-service.ts:109:15)
  at LocationMapComponent.ngOnDestroy (./src/app/analysis/location/map/location-map.component.ts:40:18)
  at Array.forEach (<anonymous>)
  at Array.forEach (<anonymous>)
  at Array.forEach (<anonymous>)
...
(45 additional frame(s) were not displayed)
```
Code:

```
      this.subscriptions.unsubscribe();
      if (this.map) {
        this.map.getView().un('change:resolution', this.updatePositionHandler);
        this.map.getView().un('change:center', this.updatePositionHandler);
      }
109>  this._map.dispose();
      this._map.setTarget(null);
     }
```

**Comment by vmarc** [comment]
The code has been changed to prevent "Error 1" and "Error 3" described above.

**Comment by vmarc** [comment]
Closing this issue as it cannot be reproduced anymore after fixing above errors.
